# Generated by Django 5.0.3 on 2024-03-20 18:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите ваше имя')),
                ('book', models.TextField(max_length=100, verbose_name='Введите название книги')),
                ('genre', models.CharField(choices=[('Романтика', 'Романтика'), ('Детектив', 'Детектив'), ('Саморазвитие', 'Саморазвитие'), ('Психология', 'Психология'), ('Исторический', 'Исторический'), ('Приключения', 'Приключения')], max_length=100, verbose_name='Выберите жанр книги')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='KG', verbose_name='Введите ваш номер телефона')),
                ('description', models.TextField(max_length=250, verbose_name='Введите краткий сюжет')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Получение книг пользователей',
            },
        ),
    ]
