# Generated by Django 5.0.3 on 2024-03-24 19:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_forum',
            name='book',
            field=models.TextField(max_length=30, verbose_name='Введите название книги'),
        ),
        migrations.CreateModel(
            name='ReviewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(10)])),
                ('name_correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='book_forum.book_forum')),
            ],
        ),
    ]
