# Generated by Django 5.0.3 on 2024-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='price',
            field=models.IntegerField(),
        ),
    ]
