# Generated by Django 5.0.3 on 2024-03-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_library_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
