# Generated by Django 5.0.3 on 2024-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_library_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='price',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
