# Generated by Django 5.0.3 on 2024-03-14 17:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_library_image_alter_library_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='library',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='Укажите вашу электронную почти'),
        ),
        migrations.AddField(
            model_name='library',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music/', verbose_name='Музыка'),
        ),
        migrations.AddField(
            model_name='library',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='KG', unique=True, verbose_name='Введите номер телефона'),
        ),
        migrations.AddField(
            model_name='library',
            name='types_books',
            field=models.CharField(choices=[('Романтика', 'Романтика'), ('Детектив', 'Детектив'), ('Саморазвитие', 'Саморазвитие'), ('Психология', 'Психология'), ('Исторический', 'Исторический'), ('Приключения', 'Приключения')], max_length=100, null=True, verbose_name='Выберите жанр'),
        ),
        migrations.AddField(
            model_name='library',
            name='youtube_url',
            field=models.URLField(null=True, verbose_name='Вставтьте URL видео с YouTube'),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='library',
            name='location',
            field=models.CharField(max_length=50, null=True, verbose_name='Место нахождение'),
        ),
        migrations.AlterField(
            model_name='library',
            name='price',
            field=models.IntegerField(default=799, max_length=20, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
