# Generated by Django 5.0.3 on 2024-03-20 17:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_library_options_library_email_library_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG', unique=True, verbose_name='Введите номер телефона'),
        ),
    ]
