# Generated by Django 5.0.3 on 2024-03-29 18:11

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_births', models.DateField()),
                ('place_of_births', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Нарын', 'Нарын'), ('Баткен', 'Баткен'), ('Исык-Куль', 'Исык-Куль'), ('Джалал-Абад', 'Джалал-Абад'), ('Чуй', 'Чуй'), ('Талас', 'Талас'), ('Ош', 'Ош')], max_length=50)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('phone_number', models.CharField(default='+996', max_length=30)),
                ('favourite_color', models.CharField(choices=[('Синий', 'Синий'), ('Красный', 'Красный'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Фиолетовый', 'Фиолетовый')], max_length=30)),
                ('hobby', models.TextField(max_length=50)),
                ('profession', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
